Pong Frontend Documentation: view_waitingInQueue Class Reference
view_waitingInQueue Class Reference
#include <view_waitinginqueue.h>
Public Member Functions
void startGame ()
~view_waitingInQueue ()
Static Public Member Functions
static view_waitingInQueue * getInstance ()
Private Member Functions
view_waitingInQueue (QWidget *parent=nullptr)
Private Attributes
Ui::view_waitingInQueue * ui
Static Private Attributes
static view_waitingInQueue * m_instance = nullptr
Constructor & Destructor Documentation
~view_waitingInQueue()
view_waitingInQueue::~view_waitingInQueue ()
References ui.
view_waitingInQueue()
view_waitingInQueue::view_waitingInQueue (QWidget * parent = nullptr) explicit private
References WebSocketClient::connectToServer(), WebSocketClient::getInstance(), and ui.
Member Function Documentation
getInstance()
view_waitingInQueue * view_waitingInQueue::getInstance () static
References m_instance.
Referenced by MenuWindow::on_btnMultiplayer_clicked(), and playerCommunicationManager::onTextMessageReceived().
startGame()
void view_waitingInQueue::startGame ()
Member Data Documentation
m_instance
view_waitingInQueue * view_waitingInQueue::m_instance = nullptr static private
Referenced by getInstance().
ui
Ui::view_waitingInQueue* view_waitingInQueue::ui private
Referenced by view_waitingInQueue(), and ~view_waitingInQueue().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/Views/view_waitinginqueue.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/Views/view_waitinginqueue.cpp