Pong Frontend Documentation: WebSocketClient Class Reference
WebSocketClient Class Reference
#include <websocketclient.h>
Signals
void connected ()
void disconnected ()
void messageReceived (const QString &message)
void error (const QString &errorString)
Public Member Functions
void connectToServer (const QUrl &url)
void sendMessage (const QString &message)
Static Public Member Functions
static WebSocketClient & getInstance ()
Private Slots
void onConnected ()
void onDisconnected ()
void onError (QAbstractSocket::SocketError error)
Private Member Functions
WebSocketClient (QObject *parent=nullptr)
~WebSocketClient ()
Private Attributes
QWebSocket * m_webSocket
playerCommunicationManager * pmm
Constructor & Destructor Documentation
WebSocketClient()
WebSocketClient::WebSocketClient (QObject * parent = nullptr) private
References m_webSocket, onConnected(), onDisconnected(), onError(), playerCommunicationManager::onTextMessageReceived(), and pmm.
~WebSocketClient()
WebSocketClient::~WebSocketClient () private
References m_webSocket.
Member Function Documentation
connected
void WebSocketClient::connected () signal
Referenced by onConnected().
connectToServer()
void WebSocketClient::connectToServer (const QUrl & url)
References m_webSocket.
Referenced by view_waitingInQueue::view_waitingInQueue().
disconnected
void WebSocketClient::disconnected () signal
Referenced by onDisconnected().
error
void WebSocketClient::error (const QString & errorString) signal
getInstance()
static WebSocketClient & WebSocketClient::getInstance () inline static
Referenced by main(), view_multiplayer::movePlayer(), and view_waitingInQueue::view_waitingInQueue().
messageReceived
void WebSocketClient::messageReceived (const QString & message) signal
onConnected
void WebSocketClient::onConnected () private slot
References connected().
Referenced by WebSocketClient().
onDisconnected
void WebSocketClient::onDisconnected () private slot
References disconnected().
Referenced by WebSocketClient().
onError
void WebSocketClient::onError (QAbstractSocket::SocketError error) private slot
Referenced by WebSocketClient().
sendMessage()
void WebSocketClient::sendMessage (const QString & message)
References m_webSocket.
Referenced by view_multiplayer::movePlayer().
Member Data Documentation
m_webSocket
QWebSocket* WebSocketClient::m_webSocket private
Referenced by connectToServer(), sendMessage(), WebSocketClient(), and ~WebSocketClient().
pmm
playerCommunicationManager* WebSocketClient::pmm private
Referenced by WebSocketClient().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/utils/websocketclient.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/utils/websocketclient.cpp