Pong Frontend Documentation: view_multiplayer Class Reference
view_multiplayer Class Reference
#include <view_multiplayer.h>
Public Member Functions
view_multiplayer (QWidget *parent=nullptr)
void updatePlayingField ()
void setPaddleColor ()
~view_multiplayer ()
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
Private Member Functions
void movePlayer ()
Private Attributes
Ui::view_multiplayer * ui
PlayerManager * m_playerManager
GameState * m_state
bool UP_pressed
bool DOWN_pressed
Constructor & Destructor Documentation
view_multiplayer()
view_multiplayer::view_multiplayer (QWidget * parent = nullptr) explicit
References PlayerManager::getInstance(), m_playerManager, movePlayer(), and ui.
~view_multiplayer()
view_multiplayer::~view_multiplayer ()
References ui.
Member Function Documentation
keyPressEvent()
void view_multiplayer::keyPressEvent (QKeyEvent * event) override protected
References DOWN_pressed, and UP_pressed.
movePlayer()
void view_multiplayer::movePlayer () private
References DOWN_pressed, WebSocketClient::getInstance(), PlayerManager::getPlayerNumber(), m_playerManager, WebSocketClient::sendMessage(), and UP_pressed.
Referenced by view_multiplayer().
setPaddleColor()
void view_multiplayer::setPaddleColor ()
References PlayerManager::getPlayerNumber(), m_playerManager, and ui.
Referenced by playerCommunicationManager::onTextMessageReceived().
updatePlayingField()
void view_multiplayer::updatePlayingField ()
References Ball::diameter, GameState::getBall(), GameState::getInstance(), GameState::getPaddle1(), GameState::getPaddle2(), GameState::getScore1(), GameState::getScore2(), Paddle::height, m_state, ui, Paddle::width, Ball::x, Paddle::x, Ball::y, and Paddle::y.
Referenced by playerCommunicationManager::onTextMessageReceived().
Member Data Documentation
DOWN_pressed
bool view_multiplayer::DOWN_pressed private
Referenced by keyPressEvent(), and movePlayer().
m_playerManager
PlayerManager* view_multiplayer::m_playerManager private
Referenced by movePlayer(), setPaddleColor(), and view_multiplayer().
m_state
GameState* view_multiplayer::m_state private
Referenced by updatePlayingField().
ui
Ui::view_multiplayer* view_multiplayer::ui private
Referenced by setPaddleColor(), updatePlayingField(), view_multiplayer(), and ~view_multiplayer().
UP_pressed
bool view_multiplayer::UP_pressed private
Referenced by keyPressEvent(), and movePlayer().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/Views/view_multiplayer.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/Views/view_multiplayer.cpp