Pong Frontend Documentation: playerCommunicationManager Class Reference
playerCommunicationManager Class Reference
#include <playercommunicationmanager.h>
Public Slots
void onTextMessageReceived (const QString &message)
Public Member Functions
playerCommunicationManager (QObject *parent=nullptr)
Private Attributes
GameState * gameState
view_multiplayer * MultiplayerView
view_FinalScore * FinalScoreView
Constructor & Destructor Documentation
playerCommunicationManager()
playerCommunicationManager::playerCommunicationManager (QObject * parent = nullptr)
References FinalScoreView, gameState, GameState::getInstance(), and MultiplayerView.
Member Function Documentation
onTextMessageReceived
void playerCommunicationManager::onTextMessageReceived (const QString & message) slot
References FinalScoreView, view_FinalScore::finalWinner(), gameState, PlayerManager::getInstance(), view_waitingInQueue::getInstance(), MultiplayerView, GameState::setBall(), GameState::setPaddle1(), GameState::setPaddle2(), view_multiplayer::setPaddleColor(), PlayerManager::setPlayerNumber(), GameState::setRunning(), GameState::setScore1(), GameState::setScore2(), PlayerManager::setUUID(), and view_multiplayer::updatePlayingField().
Referenced by WebSocketClient::WebSocketClient().
Member Data Documentation
FinalScoreView
view_FinalScore* playerCommunicationManager::FinalScoreView private
Referenced by onTextMessageReceived(), and playerCommunicationManager().
gameState
GameState* playerCommunicationManager::gameState private
Referenced by onTextMessageReceived(), and playerCommunicationManager().
MultiplayerView
view_multiplayer* playerCommunicationManager::MultiplayerView private
Referenced by onTextMessageReceived(), and playerCommunicationManager().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/playercommunicationmanager.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/playercommunicationmanager.cpp