Pong Frontend Documentation: PlayerManager Class Reference
PlayerManager Class Reference
#include <playermanager.h>
Public Member Functions
PlayerManager (PlayerManager const &)=delete
PlayerManager (PlayerManager &&)=delete
PlayerManager & operator= (PlayerManager const &)=delete
PlayerManager & operator= (PlayerManager &&)=delete
void setPlayerNumber (int p_PlayerNumber)
int getPlayerNumber ()
void setUUID (QString p_UUID)
QString getUUID ()
Static Public Member Functions
static PlayerManager & getInstance ()
Private Member Functions
PlayerManager ()
Private Attributes
int m_PlayerNumber
QString m_UUID
Constructor & Destructor Documentation
PlayerManager() [1/3]
PlayerManager::PlayerManager (PlayerManager const &) delete
PlayerManager() [2/3]
PlayerManager::PlayerManager (PlayerManager &&) delete
PlayerManager() [3/3]
PlayerManager::PlayerManager () private
Member Function Documentation
getInstance()
static PlayerManager & PlayerManager::getInstance () inline static
Referenced by playerCommunicationManager::onTextMessageReceived(), and view_multiplayer::view_multiplayer().
getPlayerNumber()
int PlayerManager::getPlayerNumber ()
References m_PlayerNumber.
Referenced by view_multiplayer::movePlayer(), and view_multiplayer::setPaddleColor().
getUUID()
QString PlayerManager::getUUID ()
References m_UUID.
operator=() [1/2]
PlayerManager & PlayerManager::operator= (PlayerManager &&) delete
operator=() [2/2]
PlayerManager & PlayerManager::operator= (PlayerManager const &) delete
setPlayerNumber()
void PlayerManager::setPlayerNumber (int p_PlayerNumber)
References m_PlayerNumber.
Referenced by playerCommunicationManager::onTextMessageReceived().
setUUID()
void PlayerManager::setUUID (QString p_UUID)
References m_UUID.
Referenced by playerCommunicationManager::onTextMessageReceived().
Member Data Documentation
m_PlayerNumber
int PlayerManager::m_PlayerNumber private
Referenced by getPlayerNumber(), and setPlayerNumber().
m_UUID
QString PlayerManager::m_UUID private
Referenced by getUUID(), and setUUID().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/playermanager.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/playermanager.cpp