Pong Frontend Documentation: GameState Class Reference
GameState Class Reference
#include <gamestate.h>
Public Member Functions
GameState (GameState const &)=delete
GameState (GameState &&)=delete
GameState & operator= (GameState const &)=delete
GameState & operator= (GameState &&)=delete
Ball getBall () const
Paddle getPaddle1 () const
Paddle getPaddle2 () const
int getScore1 () const
int getScore2 () const
bool isRunning () const
void setBall (double vx, double vy, double x, double y, double diameter)
void setPaddle1 (double x, double y, double width, double height)
void setPaddle2 (double x, double y, double width, double height)
void setScore1 (int score)
void setScore2 (int score)
void setRunning (bool running)
Static Public Member Functions
static GameState & getInstance ()
Private Member Functions
GameState ()
Private Attributes
Ball m_ball
Paddle m_paddle1
Paddle m_paddle2
int score1
int score2
bool m_running
Constructor & Destructor Documentation
GameState() [1/3]
GameState::GameState (GameState const &) delete
GameState() [2/3]
GameState::GameState (GameState &&) delete
GameState() [3/3]
GameState::GameState () private
Member Function Documentation
getBall()
Ball GameState::getBall () const
References m_ball.
Referenced by view_multiplayer::updatePlayingField().
getInstance()
static GameState & GameState::getInstance () inline static
Referenced by playerCommunicationManager::playerCommunicationManager(), and view_multiplayer::updatePlayingField().
getPaddle1()
Paddle GameState::getPaddle1 () const
References m_paddle1.
Referenced by view_multiplayer::updatePlayingField().
getPaddle2()
Paddle GameState::getPaddle2 () const
References m_paddle2.
Referenced by view_multiplayer::updatePlayingField().
getScore1()
int GameState::getScore1 () const
References score1.
Referenced by view_multiplayer::updatePlayingField().
getScore2()
int GameState::getScore2 () const
References score2.
Referenced by view_multiplayer::updatePlayingField().
isRunning()
bool GameState::isRunning () const
References m_running.
operator=() [1/2]
GameState & GameState::operator= (GameState &&) delete
operator=() [2/2]
GameState & GameState::operator= (GameState const &) delete
setBall()
void GameState::setBall (double vx, double vy, double x, double y, double diameter)
References Ball::diameter, m_ball, Ball::vx, Ball::vy, Ball::x, and Ball::y.
Referenced by playerCommunicationManager::onTextMessageReceived().
setPaddle1()
void GameState::setPaddle1 (double x, double y, double width, double height)
References Paddle::height, m_paddle1, Paddle::width, Paddle::x, and Paddle::y.
Referenced by playerCommunicationManager::onTextMessageReceived().
setPaddle2()
void GameState::setPaddle2 (double x, double y, double width, double height)
References Paddle::height, m_paddle2, Paddle::width, Paddle::x, and Paddle::y.
Referenced by playerCommunicationManager::onTextMessageReceived().
setRunning()
void GameState::setRunning (bool running)
References m_running.
Referenced by playerCommunicationManager::onTextMessageReceived().
setScore1()
void GameState::setScore1 (int score)
References score1.
Referenced by playerCommunicationManager::onTextMessageReceived().
setScore2()
void GameState::setScore2 (int score)
References score2.
Referenced by playerCommunicationManager::onTextMessageReceived().
Member Data Documentation
m_ball
Ball GameState::m_ball private
Referenced by getBall(), and setBall().
m_paddle1
Paddle GameState::m_paddle1 private
Referenced by getPaddle1(), and setPaddle1().
m_paddle2
Paddle GameState::m_paddle2 private
Referenced by getPaddle2(), and setPaddle2().
m_running
bool GameState::m_running private
Referenced by isRunning(), and setRunning().
score1
int GameState::score1 private
Referenced by getScore1(), and setScore1().
score2
int GameState::score2 private
Referenced by getScore2(), and setScore2().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/gamestate.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Frontend/ITP-Project-Frontend/gameManager/gamestate.cpp