Pong Backend Documentation: MariaDB Class Reference
MariaDB Class Reference
A class for connecting to and interacting with a MariaDB database.
#include <mariadb.h>
Public Member Functions
MariaDB (const QString &hostname, const QString &username, const QString &password, const QString &database, int port=3306)
~MariaDB ()
Destroys the MariaDB object and closes the database connection.
bool open ()
Opens a connection to the MariaDB database.
void close ()
Closes the connection to the MariaDB database.
QSqlQuery exec (const QString &query)
Executes a SQL query on the MariaDB database.
bool transaction ()
Begins a transaction on the MariaDB database.
bool commit ()
Commits a transaction on the MariaDB database.
bool rollback ()
Rolls back a transaction on the MariaDB database.
void printDebugTable (const QString &tableName)
Prints the contents of a table to the console in a table-like format.
QSqlDatabase getM_DB ()
Returns the QSqlDatabase object being used by the MariaDB class.
Private Attributes
QString m_hostname
The hostname of the MariaDB server.
QString m_username
The username to use when connecting to the MariaDB server.
QString m_password
The password to use when connecting to the MariaDB server.
QString m_database
The name of the database to use.
int m_port
The port to use when connecting to the MariaDB server.
QSqlDatabase m_db
The QSqlDatabase object used to manage the connection to the MariaDB server.
Detailed Description
A class for connecting to and interacting with a MariaDB database.
The MariaDB class allows you to connect to a MariaDB database, execute queries, and manage transactions.
Note
When building and running the project for the first time you might encounter the following error:
QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE QODBC QPSQL
Error opening database: "Driver not loaded Driver not loaded"
The Qt Company does not provide a pre-built QMYSQL driver for Windows, so you will have to build them yourself or use my prebuilt Dlls. To build them yourself, follow the instructions on the Qt Wiki. To download my prebuilt Dlls, go to the /Source/Dlls/sqldrivers and copy the files inside sqldrivers into **C:\Qt\6.4.1\mingw_64\plugins\sqldrivers**.
Examples
example_mariadb_usage.cpp.
Constructor & Destructor Documentation
MariaDB()
MariaDB::MariaDB (const QString & hostname, const QString & username, const QString & password, const QString & database, int port = 3306)
References m_db.
~MariaDB()
MariaDB::~MariaDB ()
Destroys the MariaDB object and closes the database connection.
References close().
Member Function Documentation
close()
void MariaDB::close ()
Closes the connection to the MariaDB database.
Examples
example_mariadb_usage.cpp.
References m_db.
Referenced by main(), and ~MariaDB().
commit()
bool MariaDB::commit ()
Commits a transaction on the MariaDB database.
Returns
true if the transaction was successfully committed, false otherwise.
References m_db.
exec()
QSqlQuery MariaDB::exec (const QString & query)
Executes a SQL query on the MariaDB database.
Parameters
query The SQL query to execute.
Returns
A QSqlQuery object that can be used to iterate over the query results.
Examples
example_mariadb_usage.cpp.
References m_db.
Referenced by main(), and printDebugTable().
getM_DB()
QSqlDatabase MariaDB::getM_DB ()
Returns the QSqlDatabase object being used by the MariaDB class.
Returns
The QSqlDatabase object.
Examples
example_mariadb_usage.cpp.
References m_db.
Referenced by main().
open()
bool MariaDB::open ()
Opens a connection to the MariaDB database.
Returns
true if the connection was successfully established, false otherwise.
Examples
example_mariadb_usage.cpp.
References m_database, m_db, m_hostname, m_password, m_port, and m_username.
Referenced by main().
printDebugTable()
void MariaDB::printDebugTable (const QString & tableName)
Prints the contents of a table to the console in a table-like format.
Parameters
tableName The name of the table to print.
Examples
example_mariadb_usage.cpp.
References exec().
Referenced by main().
rollback()
bool MariaDB::rollback ()
Rolls back a transaction on the MariaDB database.
Returns
true if the transaction was successfully rolled back, false otherwise.
References m_db.
transaction()
bool MariaDB::transaction ()
Begins a transaction on the MariaDB database.
Returns
true if the transaction was successfully started, false otherwise.
References m_db.
Member Data Documentation
m_database
QString MariaDB::m_database private
The name of the database to use.
Referenced by open().
m_db
QSqlDatabase MariaDB::m_db private
The QSqlDatabase object used to manage the connection to the MariaDB server.
Referenced by close(), commit(), exec(), getM_DB(), MariaDB(), open(), rollback(), and transaction().
m_hostname
QString MariaDB::m_hostname private
The hostname of the MariaDB server.
Referenced by open().
m_password
QString MariaDB::m_password private
The password to use when connecting to the MariaDB server.
Referenced by open().
m_port
int MariaDB::m_port private
The port to use when connecting to the MariaDB server.
Referenced by open().
m_username
QString MariaDB::m_username private
The username to use when connecting to the MariaDB server.
Referenced by open().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/mariadb.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/mariadb.cpp