Pong Backend Documentation: Ball Class Reference
Ball Class Reference
The Ball class represents a ball in the game.
#include <ball.h>
Public Member Functions
Ball (qreal x, qreal y, qreal radius)
Constructor for the Ball class.
QPointF getPosition ()
Get the current position of the ball.
void setVelocity (qreal xVelocity, qreal yVelocity)
Set the velocity of the ball.
QPointF getVelocity ()
Get the velocity of the ball.
void setRandomVelocity ()
Give the ball a random amount of velocity. This method should only be called at the start of a round.
void updatePosition ()
Update the position of the ball based on its velocity.
void setPosition (int x, int y)
set the position of the ball
void checkCollision (Paddle *paddle)
Check for collision between the ball and a Paddle object.
int getDiameter ()
Get the diameter of the ball.
Private Attributes
qreal m_x
The x-coordinate of the ball.
qreal m_y
The y-coordinate of the ball.
qreal m_diameter
The radius of the ball.
qreal m_xVelocity
The x-velocity of the ball.
qreal m_yVelocity
The y-velocity of the ball.
Detailed Description
The Ball class represents a ball in the game.
This class provides methods for getting and setting the position, velocity, and radius of the ball, and for updating the position of the ball based on its velocity. It also provides a method for checking collision with a Paddle object.
Constructor & Destructor Documentation
Ball()
Ball::Ball (qreal x, qreal y, qreal radius)
Constructor for the Ball class.
Parameters
x The initial x-coordinate of the ball
y The initial y-coordinate of the ball
radius The radius of the ball
References setRandomVelocity().
Member Function Documentation
checkCollision()
void Ball::checkCollision (Paddle * paddle)
Check for collision between the ball and a Paddle object.
Parameters
paddle A pointer to the Paddle object to check for collision with
References Paddle::getHeight(), Paddle::getPosition(), Paddle::getWidth(), m_diameter, m_x, m_xVelocity, m_y, and m_yVelocity.
Referenced by Game::update().
getDiameter()
int Ball::getDiameter ()
Get the diameter of the ball.
Returns
The diameter of the ball as an int
References m_diameter.
Referenced by Game::Game(), Game::reset(), and Game::sendState().
getPosition()
QPointF Ball::getPosition ()
Get the current position of the ball.
Returns
The position of the ball as a QPointF
References m_x, and m_y.
Referenced by Game::sendState(), and Game::update().
getVelocity()
QPointF Ball::getVelocity ()
Get the velocity of the ball.
Returns
The velocity of the ball as a QPointF
References m_xVelocity, and m_yVelocity.
Referenced by Game::sendState(), and Game::update().
setPosition()
void Ball::setPosition (int x, int y)
set the position of the ball
Parameters
x the x coordinate of the ball
y the y coordinate of the ball
References m_x, and m_y.
Referenced by Game::Game(), and Game::reset().
setRandomVelocity()
void Ball::setRandomVelocity ()
Give the ball a random amount of velocity. This method should only be called at the start of a round.
References m_xVelocity, and m_yVelocity.
Referenced by Ball(), and Game::reset().
setVelocity()
void Ball::setVelocity (qreal xVelocity, qreal yVelocity)
Set the velocity of the ball.
Parameters
xVelocity The x-velocity of the ball
yVelocity The y-velocity of the ball
References m_xVelocity, and m_yVelocity.
Referenced by Game::update().
updatePosition()
void Ball::updatePosition ()
Update the position of the ball based on its velocity.
References m_x, m_xVelocity, m_y, and m_yVelocity.
Referenced by Game::update().
Member Data Documentation
m_diameter
Ball::m_diameter private
The radius of the ball.
Referenced by checkCollision(), and getDiameter().
m_x
Ball::m_x private
The x-coordinate of the ball.
Referenced by checkCollision(), getPosition(), setPosition(), and updatePosition().
m_xVelocity
Ball::m_xVelocity private
The x-velocity of the ball.
Referenced by checkCollision(), getVelocity(), setRandomVelocity(), setVelocity(), and updatePosition().
m_y
Ball::m_y private
The y-coordinate of the ball.
Referenced by checkCollision(), getPosition(), setPosition(), and updatePosition().
m_yVelocity
Ball::m_yVelocity private
The y-velocity of the ball.
Referenced by checkCollision(), getVelocity(), setRandomVelocity(), setVelocity(), and updatePosition().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/ball.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/ball.cpp