Pong Backend Documentation: Paddle Class Reference
Paddle Class Reference
The Paddle class represents a paddle in the game of Pong.
#include <paddle.h>
Public Member Functions
Paddle (qreal x, qreal y, qreal width, qreal height)
Construct a new Paddle object.
void moveUp ()
Move the paddle up.
void moveDown ()
Move the paddle down.
void setDirection (int direction)
Set the direction the paddle is moving.
int getWidth ()
Get the width of the paddle.
int getHeight ()
Get the height of the paddle.
void setPosition (int x, int y)
Set the position of the paddle.
QPointF getPosition ()
Get the position of the paddle.
Private Attributes
qreal m_x
The x-coordinate of the paddle.
qreal m_y
The y-coordinate of the paddle.
qreal m_width
The width of the paddle.
qreal m_height
The height of the paddle.
int m_direction
The direction the paddle is moving @important Not yet implemented.
Detailed Description
The Paddle class represents a paddle in the game of Pong.
This class provides methods for moving the paddle and getting and setting its position and size.
Constructor & Destructor Documentation
Paddle()
Paddle::Paddle (qreal x, qreal y, qreal width, qreal height)
Construct a new Paddle object.
Parameters
x The x-coordinate of the paddle
y The y-coordinate of the paddle
width The width of the paddle
height The height of the paddle
Member Function Documentation
getHeight()
int Paddle::getHeight ()
Get the height of the paddle.
Returns
The height of the paddle as an int
References m_height.
Referenced by Ball::checkCollision(), and Game::sendState().
getPosition()
QPointF Paddle::getPosition ()
Get the position of the paddle.
Returns
The position of the paddle as a QPointF
References m_x, and m_y.
Referenced by Ball::checkCollision(), and Game::sendState().
getWidth()
int Paddle::getWidth ()
Get the width of the paddle.
Returns
The width of the paddle as an int
References m_width.
Referenced by Ball::checkCollision(), and Game::sendState().
moveDown()
void Paddle::moveDown ()
Move the paddle down.
References m_height, and m_y.
Referenced by Game::movePaddle1Down(), and Game::movePaddle2Down().
moveUp()
void Paddle::moveUp ()
Move the paddle up.
References m_y.
Referenced by Game::movePaddle1Up(), and Game::movePaddle2Up().
setDirection()
void Paddle::setDirection (int direction)
Set the direction the paddle is moving.
Parameters
direction The direction the paddle is moving (up or down)
References m_direction.
setPosition()
void Paddle::setPosition (int x, int y)
Set the position of the paddle.
Parameters
x The x-coordinate of the paddle
y The y-coordinate of the paddle
References m_x, and m_y.
Referenced by Game::reset().
Member Data Documentation
m_direction
int Paddle::m_direction private
The direction the paddle is moving @important Not yet implemented.
Referenced by setDirection().
m_height
qreal Paddle::m_height private
The height of the paddle.
Referenced by getHeight(), and moveDown().
m_width
qreal Paddle::m_width private
The width of the paddle.
Referenced by getWidth().
m_x
qreal Paddle::m_x private
The x-coordinate of the paddle.
Referenced by getPosition(), and setPosition().
m_y
qreal Paddle::m_y private
The y-coordinate of the paddle.
Referenced by getPosition(), moveDown(), moveUp(), and setPosition().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/paddle.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/paddle.cpp