Pong Backend Documentation: Game Class Reference
Game Class Reference
#include <game.h>
Public Member Functions
void update ()
Update the game state.
void start ()
Start the game.
void stop ()
Stop the game.
void reset ()
Reset the game.
void sendState ()
Send the current state of the game.
void movePaddle1Up ()
Move the left paddle up.
void movePaddle1Down ()
Move the left paddle down.
void movePaddle2Up ()
Move the right paddle up.
void movePaddle2Down ()
Move the right paddle down.
int getScore (int player)
Get the score of a player.
void setScore (int player, int score)
Set the score of a player.
Static Public Member Functions
static Game & getInstance ()
Get the singleton instance of the Game class.
Private Member Functions
Game ()
Constructor for the Game class (private to enforce singleton)
Game (Game const &)=delete
Copy constructor (deleted to prevent copying)
void operator= (Game const &)=delete
Assignment operator (deleted to prevent assignment)
Private Attributes
int m_paddleLeftX = 29
The x-coordinate of the left paddle.
int m_paddleY = 230
The y-coordinate of the paddles.
int m_paddleRightX = 625
The x-coordinate of the right paddle.
int m_winningScore = 5
The score required to win the game.
int m_score1
The score of player 1.
int m_score2
The score of player 2.
bool m_running
A flag indicating if the game is running.
QTimer * m_timer
A timer used to update the game.
int m_playingFieldWidth
The width of the playing field.
int m_playingFieldHeight
The height of the playing field.
Paddle m_paddle1
The left paddle.
Paddle m_paddle2
The right paddle.
Ball m_ball
The ball.
QJsonObject m_winnerBroadcast
The message to be broadcasted when the game ends.
LogUtils * logs
A pointer to the LogUtils class to handle logging.
MariaDB * db
A pointer to the MariaDB class to handle database operations.
Constructor & Destructor Documentation
Game() [1/2]
Game::Game () private
Constructor for the Game class (private to enforce singleton)
References LogUtils::appendData(), Ball::getDiameter(), LogUtils::getInstance(), logs, m_ball, m_playingFieldHeight, m_playingFieldWidth, m_timer, m_winnerBroadcast, Ball::setPosition(), and update().
Game() [2/2]
Game::Game (Game const &) private delete
Copy constructor (deleted to prevent copying)
Member Function Documentation
getInstance()
Game & Game::getInstance () static
Get the singleton instance of the Game class.
Returns
The Game instance
Referenced by main(), WebSocketServer::onNewConnection(), WebSocketServer::onSocketDisconnected(), and playerCommunicationManager::onTextMessageReceived().
getScore()
int Game::getScore (int player)
Get the score of a player.
Parameters
player The player (1 or 2)
Returns
The player's score
References m_score1, and m_score2.
movePaddle1Down()
void Game::movePaddle1Down ()
Move the left paddle down.
References m_paddle1, and Paddle::moveDown().
Referenced by playerCommunicationManager::onTextMessageReceived().
movePaddle1Up()
void Game::movePaddle1Up ()
Move the left paddle up.
References m_paddle1, and Paddle::moveUp().
Referenced by playerCommunicationManager::onTextMessageReceived().
movePaddle2Down()
void Game::movePaddle2Down ()
Move the right paddle down.
References m_paddle2, and Paddle::moveDown().
Referenced by playerCommunicationManager::onTextMessageReceived().
movePaddle2Up()
void Game::movePaddle2Up ()
Move the right paddle up.
References m_paddle2, and Paddle::moveUp().
Referenced by playerCommunicationManager::onTextMessageReceived().
operator=()
void Game::operator= (Game const &) private delete
Assignment operator (deleted to prevent assignment)
reset()
void Game::reset ()
Reset the game.
References Ball::getDiameter(), m_ball, m_paddle1, m_paddle2, m_paddleLeftX, m_paddleRightX, m_paddleY, m_playingFieldHeight, m_playingFieldWidth, Ball::setPosition(), Paddle::setPosition(), and Ball::setRandomVelocity().
Referenced by WebSocketServer::onSocketDisconnected(), and update().
sendState()
void Game::sendState ()
Send the current state of the game.
References LogUtils::appendData(), WebSocketServer::broadcast(), Ball::getDiameter(), Paddle::getHeight(), WebSocketServer::getInstance(), Ball::getPosition(), Paddle::getPosition(), Ball::getVelocity(), Paddle::getWidth(), logs, m_ball, m_paddle1, m_paddle2, m_running, m_score1, and m_score2.
Referenced by update().
setScore()
void Game::setScore (int player, int score)
Set the score of a player.
Parameters
player The player (1 or 2)
score The player's new score
References m_score1, and m_score2.
start()
void Game::start ()
Start the game.
References m_timer.
Referenced by WebSocketServer::onNewConnection().
stop()
void Game::stop ()
Stop the game.
Note
This method also Stops the game, Saves Logs to a CSV / Uploads them to a Database and resets the scores for m_score1 and m_score 2 to 0
References logs, m_score1, m_score2, m_timer, and LogUtils::saveToCSV().
Referenced by WebSocketServer::onSocketDisconnected(), and update().
update()
void Game::update ()
Update the game state.
References WebSocketServer::broadcast(), Ball::checkCollision(), WebSocketServer::getInstance(), Ball::getPosition(), Ball::getVelocity(), m_ball, m_paddle1, m_paddle2, m_playingFieldHeight, m_playingFieldWidth, m_score1, m_score2, m_winnerBroadcast, m_winningScore, reset(), sendState(), Ball::setVelocity(), stop(), and Ball::updatePosition().
Referenced by Game().
Member Data Documentation
db
Game::db private
A pointer to the MariaDB class to handle database operations.
logs
Game::logs private
A pointer to the LogUtils class to handle logging.
Referenced by Game(), sendState(), and stop().
m_ball
Game::m_ball private
The ball.
Referenced by Game(), reset(), sendState(), and update().
m_paddle1
Game::m_paddle1 private
The left paddle.
Referenced by movePaddle1Down(), movePaddle1Up(), reset(), sendState(), and update().
m_paddle2
Game::m_paddle2 private
The right paddle.
Referenced by movePaddle2Down(), movePaddle2Up(), reset(), sendState(), and update().
m_paddleLeftX
Game::m_paddleLeftX = 29 private
The x-coordinate of the left paddle.
Referenced by reset().
m_paddleRightX
Game::m_paddleRightX = 625 private
The x-coordinate of the right paddle.
Referenced by reset().
m_paddleY
Game::m_paddleY = 230 private
The y-coordinate of the paddles.
Referenced by reset().
m_playingFieldHeight
Game::m_playingFieldHeight private
The height of the playing field.
Referenced by Game(), reset(), and update().
m_playingFieldWidth
Game::m_playingFieldWidth private
The width of the playing field.
Referenced by Game(), reset(), and update().
m_running
Game::m_running private
A flag indicating if the game is running.
Referenced by sendState().
m_score1
Game::m_score1 private
The score of player 1.
Referenced by getScore(), sendState(), setScore(), stop(), and update().
m_score2
Game::m_score2 private
The score of player 2.
Referenced by getScore(), sendState(), setScore(), stop(), and update().
m_timer
Game::m_timer private
A timer used to update the game.
Referenced by Game(), start(), and stop().
m_winnerBroadcast
Game::m_winnerBroadcast private
The message to be broadcasted when the game ends.
Referenced by Game(), and update().
m_winningScore
Game::m_winningScore = 5 private
The score required to win the game.
Referenced by update().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/game.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/Pong/game.cpp