Pong Backend Documentation: HttpServer Class Reference
HttpServer Class Reference
A TCP server that handles HTTP requests This class is a subclass of QTcpServer and handles incoming HTTP requests. It listens for incoming connections on a specified port and invokes a callback function for each request based on the path and method specified in the request.
#include <webserver.h>
Classes
class Route
A struct representing a route in the HTTP server. A route consists of an HTTP method (e.g. GET, POST) and a callback function that is called when a request matching the method and path of the route is received.
Public Member Functions
HttpServer (QObject *parent=0)
~HttpServer ()
Destroys the HttpServer object.
bool start (quint16 port)
Starts listening for incoming connections on the specified port.
QString errorString () const
Returns a human-readable description of the last error that occurred.
void addRoute (const QString &path, const QString &method, IRouteHandler *handler)
Adds a route to the server.
Protected Member Functions
void incomingConnection (qintptr socketDescriptor)
Handles an incoming connection request.
Private Attributes
QMap< QString, Route > m_routes
A map of routes in the HTTP server, indexed by the path of the route.
Detailed Description
A TCP server that handles HTTP requests This class is a subclass of QTcpServer and handles incoming HTTP requests. It listens for incoming connections on a specified port and invokes a callback function for each request based on the path and method specified in the request.
Note
This class does not handle multiple requests concurrently. It processes one request at a time.
Constructor & Destructor Documentation
HttpServer()
HttpServer::HttpServer (QObject * parent = 0)
~HttpServer()
HttpServer::~HttpServer ()
Destroys the HttpServer object.
Member Function Documentation
addRoute()
void HttpServer::addRoute (const QString & path, const QString & method, IRouteHandler * handler)
Adds a route to the server.
Parameters
path The path of the route to add.
method The HTTP method to handle for the route.
handler The IRouteHandler object that will handle the route. This method adds a route to the server and associates it with the given IRouteHandler object. When a request is received by the server with the specified path and method, the handleRoute method of the handler object will be called.
References IRouteHandler::handleRoute(), and m_routes.
errorString()
QString HttpServer::errorString () const
Returns a human-readable description of the last error that occurred.
Returns
A QString containing the error description.
incomingConnection()
void HttpServer::incomingConnection (qintptr socketDescriptor) protected
Handles an incoming connection request.
Parameters
socketDescriptor The descriptor for the incoming connection.
Note
This method is called by the operating system when a new connection is requested.
References HttpServer::Route::callback, WSUtils::createJSONResponse(), WSUtils::isAllowedMethod(), m_routes, and HttpServer::Route::method.
start()
bool HttpServer::start (quint16 port)
Starts listening for incoming connections on the specified port.
Parameters
port The port number to listen on.
Returns
true if the server was successfully started, false otherwise.
Member Data Documentation
m_routes
QMap< QString, Route > HttpServer::m_routes private
A map of routes in the HTTP server, indexed by the path of the route.
Referenced by addRoute(), and incomingConnection().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/ws/webserver.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/ws/webserver.cpp