Pong Backend Documentation: WebSocketServer Class Reference
WebSocketServer Class Reference
A class for managing WebSocket connections.
#include <websocketserver.h>
Public Member Functions
WebSocketServer (quint16 port, QObject *parent=0)
Constructs a WebSocketServer object with the given parent.
~WebSocketServer ()
Static Public Member Functions
static void broadcast (const QString &message)
Broadcasts a message to all connected clients.
static WebSocketServer & getInstance (quint16 port=8080)
Private Slots
void onTextMessageReceived (QString message)
Handles an incoming text message.
void onNewConnection ()
Handles a new WebSocket connection.
void onBinaryMessageReceived (QByteArray message)
Handles an incoming binary message.
void onSocketDisconnected ()
Slot called when a socket is disconnected from the server This method is called when a socket is disconnected from the server. It removes the socket from the list of connected sockets, and deletes the socket object.
Private Attributes
QWebSocketServer m_socketServer
The main WebSocket server object This member variable represents the main WebSocket server object. It is used to listen for new connections, and to manage the list of connected sockets.
playerCommunicationManager * pmm
The PlayerCommunicationManager instance This member variable represents the PlayerCommunicationManager instance.
Static Private Attributes
static QList< QWebSocket * > m_sockets
List of connected sockets This static member variable represents a list of all the sockets that are currently connected to the WebSocket server. It can be accessed by any instance of the WebSocketServer class.
static WebSocketServer * m_instance = nullptr
The WebSocketServer instance This static member variable represents the WebSocketServer instance.
Detailed Description
A class for managing WebSocket connections.
This class manages WebSocket connections using a QWebSocketServer and a QList of QWebSocket objects. It provides methods for handling incoming messages, establishing new connections, and broadcasting messages to all connected clients.
Note
Code 200 - Connection established Code 201 - Received Message Code 202 - Received Binary Message
Examples
example_websocketserver_usage.cpp.
Constructor & Destructor Documentation
WebSocketServer()
WebSocketServer::WebSocketServer (quint16 port, QObject * parent = 0)
Constructs a WebSocketServer object with the given parent.
Parameters
port The port number on which to listen for incoming connections.
parent The parent object.
References m_instance, m_socketServer, onNewConnection(), and pmm.
~WebSocketServer()
WebSocketServer::~WebSocketServer ()
References m_sockets, and m_socketServer.
Member Function Documentation
broadcast()
void WebSocketServer::broadcast (const QString & message) static
Broadcasts a message to all connected clients.
Parameters
message The message to broadcast.
Examples
example_websocketserver_usage.cpp.
References m_sockets.
Referenced by HTTPTestRoute::handleRoute(), main(), onNewConnection(), Game::sendState(), and Game::update().
getInstance()
WebSocketServer & WebSocketServer::getInstance (quint16 port = 8080) static
References m_instance.
Referenced by main(), Game::sendState(), and Game::update().
onBinaryMessageReceived
void WebSocketServer::onBinaryMessageReceived (QByteArray message) private slot
Handles an incoming binary message.
References JSONUtils::generateJSON().
Referenced by onNewConnection().
onNewConnection
void WebSocketServer::onNewConnection () private slot
Handles a new WebSocket connection.
References QueueManager::addPlayer(), broadcast(), JSONUtils::generateJSON(), QueueManager::getGameId(), Game::getInstance(), QueueManager::getQueueSize(), m_sockets, m_socketServer, onBinaryMessageReceived(), onSocketDisconnected(), playerCommunicationManager::onTextMessageReceived(), pmm, Game::start(), and QueueFullException::what().
Referenced by WebSocketServer().
onSocketDisconnected
void WebSocketServer::onSocketDisconnected () private slot
Slot called when a socket is disconnected from the server This method is called when a socket is disconnected from the server. It removes the socket from the list of connected sockets, and deletes the socket object.
References JSONUtils::generateJSON(), Game::getInstance(), m_sockets, Game::reset(), QueueManager::resetQueue(), and Game::stop().
Referenced by onNewConnection().
onTextMessageReceived
void WebSocketServer::onTextMessageReceived (QString message) private slot
Handles an incoming text message.
Parameters
message The incoming text message.
Deprecated:
This Slot is deprecated and has been replaced by the playermovementmanager class.
Member Data Documentation
m_instance
WebSocketServer * WebSocketServer::m_instance = nullptr static private
The WebSocketServer instance This static member variable represents the WebSocketServer instance.
Referenced by getInstance(), and WebSocketServer().
m_sockets
QList< QWebSocket * > WebSocketServer::m_sockets static private
List of connected sockets This static member variable represents a list of all the sockets that are currently connected to the WebSocket server. It can be accessed by any instance of the WebSocketServer class.
Referenced by broadcast(), onNewConnection(), onSocketDisconnected(), and ~WebSocketServer().
m_socketServer
QWebSocketServer WebSocketServer::m_socketServer private
The main WebSocket server object This member variable represents the main WebSocket server object. It is used to listen for new connections, and to manage the list of connected sockets.
Referenced by onNewConnection(), WebSocketServer(), and ~WebSocketServer().
pmm
playerCommunicationManager* WebSocketServer::pmm private
The PlayerCommunicationManager instance This member variable represents the PlayerCommunicationManager instance.
Referenced by onNewConnection(), and WebSocketServer().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/socket/websocketserver.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/socket/websocketserver.cpp