Pong Backend Documentation: LogUtils Class Reference
LogUtils Class Reference
#include <logs.h>
Public Member Functions
void appendData (const QStringList &data)
void saveToCSV (const QString &fileName)
void setMaxRows (unsigned int maxRows)
void setMaxBufferSize (unsigned int maxBufferSize)
Static Public Member Functions
static LogUtils & getInstance ()
Private Member Functions
LogUtils ()
Private Attributes
QList< QStringList > m_data
unsigned int m_maxRows
unsigned int m_maxBufferSize
Constructor & Destructor Documentation
LogUtils()
LogUtils::LogUtils () private
References m_maxBufferSize, and m_maxRows.
Member Function Documentation
appendData()
void LogUtils::appendData (const QStringList & data)
References m_data, and m_maxRows.
Referenced by Game::Game(), and Game::sendState().
getInstance()
LogUtils & LogUtils::getInstance () static
Referenced by Game::Game().
saveToCSV()
void LogUtils::saveToCSV (const QString & fileName)
References m_data, and m_maxBufferSize.
Referenced by Game::stop().
setMaxBufferSize()
void LogUtils::setMaxBufferSize (unsigned int maxBufferSize)
References m_maxBufferSize.
setMaxRows()
void LogUtils::setMaxRows (unsigned int maxRows)
References m_maxRows.
Member Data Documentation
m_data
QList<QStringList> LogUtils::m_data private
Referenced by appendData(), and saveToCSV().
m_maxBufferSize
unsigned int LogUtils::m_maxBufferSize private
Referenced by LogUtils(), saveToCSV(), and setMaxBufferSize().
m_maxRows
unsigned int LogUtils::m_maxRows private
Referenced by appendData(), LogUtils(), and setMaxRows().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/logs.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/logs.cpp