Pong Backend Documentation: WSUtils Class Reference
WSUtils Class Reference
Utility class for handling web server related tasks.
#include <ws_utils.h>
Public Member Functions
WSUtils ()
Constructs a new WSUtils object.
Static Public Member Functions
static std::string createJSONResponse (std::string p_content)
Creates a JSON HTTP response with the given content.
static std::string createHTMLResponse (std::string p_content)
Creates an HTML HTTP response with the given content.
static bool isAllowedMethod (const QString &method)
Checks if the given HTTP request method is allowed.
Static Private Attributes
static QStringList m_allowedMethods = {"GET", "POST", "PUT", "DELETE"}
List of allowed HTTP request methods.
Detailed Description
Utility class for handling web server related tasks.
This class provides static methods for creating HTTP responses in the form of JSON or HTML, as well as a method for checking if a given HTTP request method is allowed.
Constructor & Destructor Documentation
WSUtils()
WSUtils::WSUtils ()
Constructs a new WSUtils object.
Member Function Documentation
createHTMLResponse()
std::string WSUtils::createHTMLResponse (std::string p_content) static
Creates an HTML HTTP response with the given content.
Parameters
p_content The content to include in the response
Returns
The HTML HTTP response as a string
Referenced by HTTPTestRoute::handleRoute().
createJSONResponse()
std::string WSUtils::createJSONResponse (std::string p_content) static
Creates a JSON HTTP response with the given content.
Parameters
p_content The content to include in the response
Returns
The JSON HTTP response as a string
Referenced by JSONTestRoute::handleRoute(), and HttpServer::incomingConnection().
isAllowedMethod()
bool WSUtils::isAllowedMethod (const QString & method) static
Checks if the given HTTP request method is allowed.
Parameters
method The HTTP request method to check
Returns
True if the method is allowed, false otherwise
References m_allowedMethods.
Referenced by HttpServer::incomingConnection().
Member Data Documentation
m_allowedMethods
QStringList WSUtils::m_allowedMethods = {"GET", "POST", "PUT", "DELETE"} static private
List of allowed HTTP request methods.
Referenced by isAllowedMethod().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/ws_utils.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/ws_utils.cpp