Pong Backend Documentation: JSONUtils Class Reference
JSONUtils Class Reference
A class for generating JSON strings from a map of key-value pairs.
#include <jsonutils.h>
Public Types
using Value = std::variant< int, bool, std::string >
A variant type that can hold int, bool, or std::string values.
Public Member Functions
JSONUtils ()
Constructs a new JSONUtils object.
Static Public Member Functions
static std::string generateJSON (const std::map< std::string, Value > &data)
Generates a JSON string from the given data.
Detailed Description
A class for generating JSON strings from a map of key-value pairs.
Member Typedef Documentation
Value
using JSONUtils::Value = std::variant<int, bool, std::string>
A variant type that can hold int, bool, or std::string values.
Constructor & Destructor Documentation
JSONUtils()
JSONUtils::JSONUtils ()
Constructs a new JSONUtils object.
Member Function Documentation
generateJSON()
std::string JSONUtils::generateJSON (const std::map< std::string, Value > & data) static
Generates a JSON string from the given data.
Parameters
data A map of key-value pairs to include in the JSON string.
Returns
The generated JSON string.
Referenced by JSONTestRoute::handleRoute(), WebSocketServer::onBinaryMessageReceived(), WebSocketServer::onNewConnection(), and WebSocketServer::onSocketDisconnected().
The documentation for this class was generated from the following files:
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/jsonutils.h
C:/Users/JNSAP/Documents/GitHub/ITP-Project-1/Source/Backend/ITP-Project/utils/jsonutils.cpp